Floating Edge Check - Add Minimum Highway Type
sayas01/atlas-checks pull request #2
Opened 2018-10-01 02:48 UTC by sayas01

This PR adds a value - `minimum highway type` in the configurable. All the highway tags that have lower priority than the set minimum highway type will not be considered for the check. If no value is given in the configuration file, then the default type of `Highway = RACEWAY` will be set as minimum.

2018-10-01 16:58 UTC, Bentleysb approved these changes
This looks good. I am curious why raceway was selected as the default. That is not a minimum I have seen used before.

2018-10-01 17:03 UTC, sayas01 commented
@Bentleysb Based on the analysis, it was found that edges with highway tag = road and below created a considerable number of false positives for FloatingEdgeCheck. Hence now this check will only consider those edges with highway tag having higher priority than road.

2018-10-01 18:11 UTC, nachtm approved these changes
LGTM! Just one comment about variable names.

2018-10-01 18:11 UTC, nachtm commented on src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheckTest.java
> +    private FloatingEdgeCheck check2 = new FloatingEdgeCheck(
Maybe name this something like primaryLinkCheck?

2018-10-01 18:14 UTC, Bentleysb commented on config/configuration.json
> +    "minimum.highway.type": "raceway",
Just spotted this one little thing. 

Nit: `highway.minimum` might be simpler and clearer.

2018-10-01 18:22 UTC, danielduhh requested changes
Just echoing some comments about variable names

2018-10-01 18:22 UTC, danielduhh commented on config/configuration.json
> +    "minimum.highway.type": "raceway",
Yup

2018-10-01 18:22 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
> +    private static final String MINIMUM_HIGHWAY_TYPE_DEFAULT = HighwayTag.RACEWAY.toString();
`HIGHWAY_MINIMUM_DEFAULT`

2018-10-01 18:22 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
> +    private final HighwayTag minimumHighwayType;
`highwayMinimum`

2018-10-01 18:22 UTC, danielduhh commented on src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheckTest.java
> +    private FloatingEdgeCheck check2 = new FloatingEdgeCheck(
Yup

2018-10-10 06:23 UTC, danielduhh approved these changes

2018-10-10 06:25 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
> +     * default highway type of "RACEWAY" will be set as minimum.
Comment needs updating

2018-10-10 06:26 UTC, danielduhh commented
Changes look good - thanks for the updates. There's a reference to raceway in one of your comments that needs to be updated.

When submitting to origin, please be descriptive as possible in the initial PR comment. For example, you need to justify WHY you've decided to add a highway classification configurable and WHY that configurable value is service. This will act as a high level description of the analysis results

2018-10-11 16:24 UTC, closed without merging